// Posiciones de candidatos presidenciales 2026 por tema (escala 1-5)
// 1 = Izquierda/Progresista, 5 = Derecha/Conservador, 3 = Centro
// Basado en planes de gobierno oficiales presentados al JNE

export interface CandidatePosition {
  candidateId: string
  candidateName: string
  candidateSlug: string
  partyName: string
  photoUrl?: string
  positions: Record<string, number>
}

export const CANDIDATE_POSITIONS: CandidatePosition[] = [
  {
    candidateId: 'keiko-fujimori',
    candidateName: 'Keiko Fujimori',
    candidateSlug: 'keiko-fujimori',
    partyName: 'Fuerza Popular',
    positions: {
      security: 5,
      economy: 5,
      education: 4,
      health: 4,
      mining: 5,
      pensions: 4,
      corruption: 4,
      decentralization: 3,
      foreign_policy: 5,
      political_reform: 5,
    },
  },
  {
    candidateId: 'lopez-aliaga',
    candidateName: 'Rafael López Aliaga',
    candidateSlug: 'lopez-aliaga-cazorla-rafael-bernardo',
    partyName: 'Renovación Popular',
    positions: {
      security: 5,
      economy: 5,
      education: 4,
      health: 4,
      mining: 5,
      pensions: 4,
      corruption: 4,
      decentralization: 4,
      foreign_policy: 5,
      political_reform: 5,
    },
  },
  {
    candidateId: 'george-forsyth',
    candidateName: 'George Forsyth',
    candidateSlug: 'george-forsyth',
    partyName: 'Somos Perú',
    positions: {
      security: 4,
      economy: 3,
      education: 2,
      health: 2,
      mining: 3,
      pensions: 3,
      corruption: 3,
      decentralization: 3,
      foreign_policy: 3,
      political_reform: 3,
    },
  },
  {
    candidateId: 'cerron-rojas',
    candidateName: 'Vladimir Cerrón',
    candidateSlug: 'cerron-rojas-vladimir-roy',
    partyName: 'Perú Libre',
    positions: {
      security: 3,
      economy: 1,
      education: 1,
      health: 1,
      mining: 1,
      pensions: 1,
      corruption: 3,
      decentralization: 1,
      foreign_policy: 1,
      political_reform: 1,
    },
  },
  {
    candidateId: 'cesar-acuna',
    candidateName: 'César Acuña',
    candidateSlug: 'd6fe3cac-7061-474b-8551-0aa686a54bad-jpg',
    partyName: 'Alianza para el Progreso',
    positions: {
      security: 4,
      economy: 4,
      education: 3,
      health: 3,
      mining: 4,
      pensions: 4,
      corruption: 3,
      decentralization: 3,
      foreign_policy: 3,
      political_reform: 3,
    },
  },
  {
    candidateId: 'jose-williams',
    candidateName: 'José Williams',
    candidateSlug: 'jose-williams',
    partyName: 'Avanza País',
    positions: {
      security: 5,
      economy: 5,
      education: 3,
      health: 3,
      mining: 4,
      pensions: 3,
      corruption: 4,
      decentralization: 3,
      foreign_policy: 5,
      political_reform: 4,
    },
  },
  {
    candidateId: 'yonhy-lescano',
    candidateName: 'Yonhy Lescano',
    candidateSlug: 'yonhy-lescano',
    partyName: 'Cooperación Popular',
    positions: {
      security: 3,
      economy: 2,
      education: 2,
      health: 2,
      mining: 2,
      pensions: 2,
      corruption: 3,
      decentralization: 2,
      foreign_policy: 2,
      political_reform: 2,
    },
  },
  {
    candidateId: 'jorge-nieto',
    candidateName: 'Jorge Nieto',
    candidateSlug: 'jorge-nieto',
    partyName: 'Partido del Buen Gobierno',
    positions: {
      security: 4,
      economy: 3,
      education: 3,
      health: 3,
      mining: 3,
      pensions: 3,
      corruption: 3,
      decentralization: 3,
      foreign_policy: 3,
      political_reform: 3,
    },
  },
  {
    candidateId: 'luna-galvez',
    candidateName: 'José Luna Gálvez',
    candidateSlug: 'luna-galvez-jose-leon',
    partyName: 'Podemos Perú',
    positions: {
      security: 4,
      economy: 3,
      education: 2,
      health: 2,
      mining: 3,
      pensions: 2,
      corruption: 3,
      decentralization: 2,
      foreign_policy: 3,
      political_reform: 2,
    },
  },
  {
    candidateId: 'valderrama',
    candidateName: 'Enrique Valderrama',
    candidateSlug: 'enrique-valderrama',
    partyName: 'Partido Aprista Peruano',
    positions: {
      security: 3,
      economy: 3,
      education: 2,
      health: 2,
      mining: 3,
      pensions: 2,
      corruption: 3,
      decentralization: 2,
      foreign_policy: 2,
      political_reform: 3,
    },
  },
  {
    candidateId: 'vizcarra',
    candidateName: 'Martín Vizcarra',
    candidateSlug: 'vizcarra-cornejo-mario-enrique',
    partyName: 'Perú Primero',
    positions: {
      security: 3,
      economy: 3,
      education: 3,
      health: 2,
      mining: 3,
      pensions: 3,
      corruption: 3,
      decentralization: 2,
      foreign_policy: 3,
      political_reform: 2,
    },
  },
  {
    candidateId: 'perez-tello',
    candidateName: 'Marisol Pérez Tello',
    candidateSlug: '073703ca-c427-44f0-94b1-a782223a5e10-jpg',
    partyName: 'Primero la Gente',
    positions: {
      security: 3,
      economy: 3,
      education: 2,
      health: 2,
      mining: 3,
      pensions: 3,
      corruption: 3,
      decentralization: 2,
      foreign_policy: 3,
      political_reform: 3,
    },
  },
  {
    candidateId: 'molinelli',
    candidateName: 'Fiorella Molinelli',
    candidateSlug: '1de656b5-7593-4c60-ab7a-83d618a3d80d-jpg',
    partyName: 'Fuerza y Libertad',
    positions: {
      security: 4,
      economy: 4,
      education: 3,
      health: 3,
      mining: 4,
      pensions: 3,
      corruption: 3,
      decentralization: 3,
      foreign_policy: 3,
      political_reform: 4,
    },
  },
  {
    candidateId: 'belmont',
    candidateName: 'Ricardo Belmont',
    candidateSlug: 'belmont-cassinelli-ricardo-pablo',
    partyName: 'Cívico Obras',
    positions: {
      security: 4,
      economy: 4,
      education: 3,
      health: 3,
      mining: 4,
      pensions: 3,
      corruption: 3,
      decentralization: 2,
      foreign_policy: 3,
      political_reform: 3,
    },
  },
  {
    candidateId: 'olivera',
    candidateName: 'Fernando Olivera',
    candidateSlug: 'olivera-vega-luis-fernando',
    partyName: 'Frente de la Esperanza',
    positions: {
      security: 4,
      economy: 4,
      education: 3,
      health: 3,
      mining: 4,
      pensions: 3,
      corruption: 4,
      decentralization: 3,
      foreign_policy: 4,
      political_reform: 4,
    },
  },
  {
    candidateId: 'guevara',
    candidateName: 'Mesías Guevara',
    candidateSlug: '1b861ca7-3a5e-48b4-9024-08a92371e33b-jpg',
    partyName: 'Partido Morado',
    positions: {
      security: 3,
      economy: 2,
      education: 2,
      health: 2,
      mining: 2,
      pensions: 2,
      corruption: 2,
      decentralization: 2,
      foreign_policy: 2,
      political_reform: 2,
    },
  },
  {
    candidateId: 'jaimes-blanco',
    candidateName: 'Paul Jaimes Blanco',
    candidateSlug: '929e1a63-335d-4f3a-ba26-f3c7ff136213-jpg',
    partyName: 'Progresemos',
    positions: {
      security: 3,
      economy: 2,
      education: 1,
      health: 2,
      mining: 2,
      pensions: 2,
      corruption: 2,
      decentralization: 2,
      foreign_policy: 2,
      political_reform: 2,
    },
  },
  {
    candidateId: 'sanchez-palomino',
    candidateName: 'Roberto Sánchez Palomino',
    candidateSlug: 'bb7c7465-9c6e-44eb-ac7d-e6cc7f872a1a-jpg',
    partyName: 'Juntos por el Perú',
    positions: {
      security: 3,
      economy: 1,
      education: 1,
      health: 1,
      mining: 1,
      pensions: 1,
      corruption: 2,
      decentralization: 1,
      foreign_policy: 1,
      political_reform: 1,
    },
  },
  {
    candidateId: 'belaunde-llosa',
    candidateName: 'Rafael Belaúnde Llosa',
    candidateSlug: '3302e45b-55c8-4979-a60b-2b11097abf1d-jpg',
    partyName: 'Libertad Popular',
    positions: {
      security: 4,
      economy: 5,
      education: 4,
      health: 3,
      mining: 4,
      pensions: 3,
      corruption: 4,
      decentralization: 3,
      foreign_policy: 4,
      political_reform: 3,
    },
  },
  {
    candidateId: 'diez-canseco',
    candidateName: 'Francisco Diez-Canseco',
    candidateSlug: 'diez-canseco-tavara-francisco-ernesto',
    partyName: 'Perú Acción',
    positions: {
      security: 5,
      economy: 5,
      education: 4,
      health: 3,
      mining: 4,
      pensions: 3,
      corruption: 5,
      decentralization: 4,
      foreign_policy: 5,
      political_reform: 4,
    },
  },
]

// Funcion para obtener posicion de candidato por tema
export function getCandidatePosition(candidateSlug: string, topic: string): number | null {
  const candidate = CANDIDATE_POSITIONS.find(c => c.candidateSlug === candidateSlug)
  return candidate?.positions[topic] ?? null
}
